services:
  django:
      container_name: django
      build: .
      volumes:
        - ./:/app
      ports:
        - 8000:8000
  redis:
    image: redis:7.2.8
    container_name: redis
    ports:
      - 6379:6379