[project]
name = "generala"
version = "0.1.0"
description = "A multiplayer game of 'generala'"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["channels[daphne]>=4.2.2", "django>=5.2", "ruff>=0.11.7"]
