[project]
name = "generala"
version = "0.1.0"
description = "A multiplayer game of 'generala'"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "channels-redis>=4.2.1",
    "channels[daphne]>=4.2.2",
    "django>=5.2",
    "pydantic>=2.11.4",
    "ruff>=0.11.7",
]
